#!/usr/bin/env bash
# =============================================================================
# AIORCH — Interactive Docker Installer
# Usage: curl -fsSL https://aiorch.ai/install.sh | bash
# =============================================================================
# This script downloads and configures the AIORCH Docker image.
# No source code is downloaded — only the compiled Docker image.
# Requires: Docker, Docker Compose
# =============================================================================

set -euo pipefail

REGISTRY="aiorch/orchestrator"
DEFAULT_TAG="latest"
LICENSE_URL="https://license.aiorch.ai"

echo ""
echo "╔═══════════════════════════════════════╗"
echo "║   AIORCH — AI Code Orchestration      ║"
echo "║   https://aiorch.ai                   ║"
echo "╚═══════════════════════════════════════╝"
echo ""

# --- Check Docker ---
if ! command -v docker &>/dev/null; then
    echo "[MISSING] Docker is required."
    echo ""
    echo "  Install Docker:"
    echo "    curl -fsSL https://get.docker.com | sh"
    echo ""
    echo "  After installing, run this script again."
    echo ""
    read -p "Press Enter to exit..." < /dev/tty
    exit 1
fi
echo "[OK] Docker $(docker --version | grep -oP '\d+\.\d+\.\d+')"

# --- Check Docker Compose ---
if ! docker compose version &>/dev/null 2>&1; then
    echo "[MISSING] Docker Compose is required."
    echo "  Install: apt install docker-compose-plugin"
    read -p "Press Enter to exit..." < /dev/tty
    exit 1
fi
echo "[OK] Docker Compose $(docker compose version --short 2>/dev/null)"

# --- Check Docker starts on boot ---
if command -v systemctl &>/dev/null; then
    if ! systemctl is-enabled docker &>/dev/null 2>&1; then
        echo "[WARN] Docker is NOT enabled to start on boot."
        echo "  Fix: sudo systemctl enable docker"
        echo ""
    fi
fi

# --- Claude CLI ---
CLAUDE_CLI_PATH=""
CLAUDE_CONFIG_PATH=""
if command -v claude &>/dev/null; then
    CLAUDE_CLI_PATH="$(command -v claude)"
    echo "[OK] Claude CLI: ${CLAUDE_CLI_PATH}"
    if [ -d "${HOME}/.claude" ]; then
        CLAUDE_CONFIG_PATH="${HOME}/.claude"
    fi
else
    echo -e "${YELLOW}[INFO] Claude CLI not found — needed for Claude models.${NC}"
    echo ""
    echo "  To install Claude CLI:"
    echo "    curl -fsSL https://claude.ai/install.sh | bash"
    echo "    claude  # Run once to authenticate"
    echo ""
    echo "  After installing, restart AIORCH to pick it up:"
    echo "    cd /opt/aiorch && docker compose restart"
    echo ""
    echo "  OpenAI and Ollama models work without Claude CLI."
    echo ""
fi

# --- Install directory ---
echo ""
read -p "Install directory [/opt/aiorch]: " INSTALL_DIR < /dev/tty
INSTALL_DIR=${INSTALL_DIR:-/opt/aiorch}

if [ -d "${INSTALL_DIR}" ] && [ -f "${INSTALL_DIR}/docker-compose.yml" ]; then
    echo "[INFO] Existing installation found at ${INSTALL_DIR}"
    read -p "Overwrite configuration? (y/N): " OVERWRITE < /dev/tty
    if [ "${OVERWRITE}" != "y" ] && [ "${OVERWRITE}" != "Y" ]; then
        echo "Aborting. Existing installation preserved."
        exit 0
    fi
fi
mkdir -p "${INSTALL_DIR}/data"

# --- Port ---
read -p "Port [1230]: " PORT < /dev/tty
PORT=${PORT:-1230}

# --- License key ---
echo ""
echo "  License key activates the full product."
echo "  Leave empty for a 14-day free trial."
echo "  Purchase at: https://aiorch.ai/pricing"
echo ""
read -p "License key: " LICENSE_KEY < /dev/tty

# --- Pull image ---
IMAGE_TAG="${DEFAULT_TAG}"
echo ""
echo "Pulling AIORCH image..."
docker pull "${REGISTRY}:${IMAGE_TAG}"

# --- Generate secrets ---
if command -v python3 &>/dev/null; then
    SESSION_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(32))")
    API_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
elif command -v openssl &>/dev/null; then
    SESSION_SECRET=$(openssl rand -hex 32)
    API_KEY=$(openssl rand -base64 48 | tr -d '=/+' | head -c 48)
else
    SESSION_SECRET=$(head -c 32 /dev/urandom | xxd -p | tr -d '\n')
    API_KEY=$(head -c 48 /dev/urandom | base64 | tr -d '=/+' | head -c 48)
fi

# --- Generate .env ---
cat > "${INSTALL_DIR}/.env" << ENVEOF
# AIORCH — Generated by install.sh
# Documentation: https://aiorch.ai/docs

# Server
ORCH_HOST=0.0.0.0
ORCH_PORT=${PORT}
ORCH_LOG_LEVEL=INFO

# Authentication — required for API access (auto-generated)
ORCH_API_KEY=${API_KEY}

# Paths (inside container)
ORCH_BASE_DIR=/opt/aiorch
ORCH_SESSIONS_DIR=/opt/aiorch/data/sessions
ORCH_PIPELINES_DIR=/opt/aiorch/data/pipelines
ORCH_DATA_DIR=/opt/aiorch/data

# Models (configure via /settings page after install)
ORCH_DEFAULT_MODEL=opus
ORCH_DEFAULT_PLANNING_MODEL=
ORCH_DEFAULT_REVIEW_MODEL=
ORCH_OPENAI_API_KEY=
ORCH_OPENAI_BASE_URL=https://api.openai.com/v1
ORCH_OLLAMA_BASE_URL=http://localhost:11434

# GitHub PR creation
ORCH_GITHUB_TOKEN=

# License
ORCH_LICENSE_KEY=${LICENSE_KEY}
ORCH_LICENSE_URL=${LICENSE_URL}
ORCH_LICENSE_HEARTBEAT_INTERVAL=300
ORCH_LICENSE_GRACE_HOURS=24
ORCH_LICENSE_STALE_TIMEOUT_MINUTES=10

# Agent defaults
ORCH_MAX_PARALLEL_AGENTS=4
ORCH_MAX_REVIEW_ROUNDS=3
ORCH_MAX_AGENTS_PER_SESSION=10

# Polling
ORCH_POLL_INTERVAL=15
ORCH_PIPELINE_POLL_INTERVAL=20
ORCH_AUTO_START_POLL_INTERVAL=30
ORCH_ZOMBIE_RECOVERY_INTERVAL=60

# Security
ORCH_SESSION_SECRET=${SESSION_SECRET}
ORCH_SETTINGS_SESSION_EXPIRY_MINUTES=30
ORCH_RATE_LIMIT_RPM=120

# Resilience
ORCH_AGENT_EXECUTION_TIMEOUT=1800
ORCH_PARENT_WAIT_TIMEOUT=7200
ORCH_MAX_AGENT_RETRIES=1

# Tool-use loop
ORCH_MAX_TOOL_ITERATIONS=50
ORCH_TOOL_CMD_TIMEOUT=60
ORCH_TOOL_CMD_OUTPUT_CAP=10240
ORCH_TOOL_MAX_CONSECUTIVE_ERRORS=3
ORCH_TOOL_LOOP_TEMPERATURE=0.3

# Docker
ORCH_DOCKER_REGISTRY=${REGISTRY}
ORCH_IMAGE_TAG=${IMAGE_TAG}

# Support (set to your company/email for ticket correlation)
ORCH_SUPPORT_ID=
ENVEOF

echo "[OK] Config: ${INSTALL_DIR}/.env"

# --- Generate docker-compose.yml ---
VOLUMES="      - ./data:/opt/aiorch/data"
if [ -n "${CLAUDE_CLI_PATH}" ]; then
    VOLUMES="${VOLUMES}
      - ${CLAUDE_CLI_PATH}:/usr/local/bin/claude:ro"
fi
if [ -n "${CLAUDE_CONFIG_PATH}" ]; then
    VOLUMES="${VOLUMES}
      - ${CLAUDE_CONFIG_PATH}:/root/.claude:ro"
fi

cat > "${INSTALL_DIR}/docker-compose.yml" << DEOF
services:
  orchestrator:
    image: ${REGISTRY}:${IMAGE_TAG}
    ports:
      - "${PORT}:${PORT}"
    volumes:
${VOLUMES}
    env_file:
      - .env
    environment:
      - PYTHONPATH=/opt/aiorch
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
DEOF

echo "[OK] Compose: ${INSTALL_DIR}/docker-compose.yml"

# --- Start ---
echo ""
echo "Starting AIORCH..."
cd "${INSTALL_DIR}"
docker compose up -d

GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                               ║${NC}"
echo -e "${GREEN}║   ${BOLD}AIORCH is running!${NC}${GREEN}                                        ║${NC}"
echo -e "${GREEN}║                                                               ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Dashboard:${NC}  ${CYAN}http://localhost:${PORT}${NC}"
echo ""
echo -e "  ${YELLOW}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "  ${YELLOW}║  ${BOLD}API KEY (for scripts, CI, and external integrations)${NC}${YELLOW}    ║${NC}"
echo -e "  ${YELLOW}║                                                           ║${NC}"
echo -e "  ${YELLOW}║${NC}  ${BOLD}${API_KEY}${NC}"
echo -e "  ${YELLOW}║                                                           ║${NC}"
echo -e "  ${YELLOW}║  ${DIM}Browser login uses master password, not this key.${NC}${YELLOW}        ║${NC}"
echo -e "  ${YELLOW}║  ${DIM}Stored in: ${INSTALL_DIR}/.env${NC}${YELLOW}                            ║${NC}"
echo -e "  ${YELLOW}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Config:${NC}     ${DIM}${INSTALL_DIR}/.env${NC}"
echo -e "  ${BOLD}Data:${NC}       ${DIM}${INSTALL_DIR}/data${NC}"
echo ""
echo -e "  ${GREEN}Next steps:${NC}"
echo -e "    ${BOLD}1.${NC} Open ${CYAN}http://localhost:${PORT}/settings${NC}"
echo -e "    ${BOLD}2.${NC} Set your master password"
echo -e "    ${BOLD}3.${NC} Configure API keys (OpenAI, Claude, etc.)"
echo -e "    ${BOLD}4.${NC} Create your first session!"
echo ""
if [ -z "${LICENSE_KEY}" ]; then
    echo -e "  ${DIM}Trial: 14 days remaining${NC}"
    echo -e "  ${DIM}Purchase: ${CYAN}https://aiorch.ai/pricing${NC}"
    echo ""
fi
echo -e "  ${DIM}Commands:${NC}"
echo -e "    ${DIM}docker compose logs -f${NC}      ${DIM}# View logs${NC}"
echo -e "    ${DIM}docker compose restart${NC}      ${DIM}# Restart${NC}"
echo -e "    ${DIM}docker compose down${NC}         ${DIM}# Stop${NC}"
echo -e "    ${DIM}docker compose pull && docker compose up -d${NC}  ${DIM}# Update${NC}"
echo ""
if [ -n "${PORT}" ] && [ "${PORT}" != "1230" ]; then
    echo -e "  ${YELLOW}Note: If on a remote server, ensure port ${PORT} is accessible.${NC}"
    echo ""
fi
